#! /bin/bash
usage_error () {
	cd ..
}


newpwd() {
  oldpwd=$1
  case "$2" in
    -s)
      pattern=$3
      NEWPWD=$(echo $oldpwd | sed 's|\(.*/'$pattern'[^/]*/\).*|\1|')
      ;;
    -si)
      pattern=$3
      NEWPWD=$(echo $oldpwd | perl -pe 's|(.*/'$pattern'[^/]*/).*|$1|i')
      ;;
    *)
      pattern=$2
      NEWPWD=$(echo $oldpwd | sed 's|\(.*/'$pattern'/\).*|\1|')
  esac
}

if [ $# -eq 0 ]
then
  usage_error
elif [ "${@: -1}" = -v ]
then
  usage_error
else
  oldpwd=$(pwd)

  newpwd "$oldpwd" "$@"
  
  if [ "$NEWPWD" = "$oldpwd" ]
  then
    echo "No such occurrence."
  else
    cd "$NEWPWD"
  fi
  unset NEWPWD
fi
